version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biocad
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./back
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/biocad
      JWT_SECRET: jwt_secret
    ports:
      - "4200:4200"
    # volumes:
    #   - ./back:/app
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  pgdata:
